In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sp
import matplotlib.pyplot as plt
import seaborn as sns 
import scipy.stats as stats

In [ ]:
wine = pd.read_csv('wine.csv')

In [ ]:
wine.head()

In [ ]:
# pip install pandas_profiling

In [ ]:
import pandas_profiling
profile = wine.profile_report()

In [ ]:
profile.to_file('wine_profile.html')

In [ ]:
wine = wine[~wine.duplicated(wine.columns, keep='last')]

In [ ]:
# !pip install sweetviz

In [ ]:
import sweetviz

In [ ]:
eda_report=sweetviz.analyze(wine)
eda_report.show_html()

---

In [ ]:
wine.columns = ['고정산', '휘발산', '구연산', '잔여당', '염화물', '무수아황산', '총이산화황', 
                '밀도', '산성도', '황산염', '알콜도수', '와인품질', '와인종류'] 

In [ ]:
wine.info()

In [ ]:
wine.describe()

In [ ]:
plt.rcParams['font.family'] = 'Malgun Gothic'

In [ ]:
plt.figure(figsize=(12,12))
for i in range(0,11):    
    plt.subplot(3,4,i+1)
    sns.distplot(wine.iloc[:,i])
plt.tight_layout()
plt.show()

In [ ]:
pd.DataFrame(wine.와인품질.value_counts())

In [ ]:
sns.countplot(x='와인품질', data=wine)
plt.grid()
plt.show()

In [ ]:
pd.DataFrame(wine.와인종류.value_counts())

In [ ]:
plt.figure(figsize=(3, 5)) 
sns.countplot(x='와인종류', palette=sns.color_palette('Set3'), data = wine)
plt.grid()
plt.show()

In [ ]:
plt.figure(figsize=(8, 6)) 
sns.countplot(x='와인품질',hue='와인종류', data=wine)
plt.grid()
plt.show()

In [ ]:
wine_corr = wine.corr()

In [ ]:
wine_corr

In [ ]:
pd.DataFrame(wine_corr.와인품질.sort_values(ascending = False))

In [ ]:
pd.DataFrame(wine_corr.loc[wine_corr.와인품질 > 0, '와인품질'])

In [ ]:
pd.DataFrame(wine_corr.loc[wine_corr.와인품질 < 0, '와인품질'])

In [ ]:
sns.pairplot(wine, kind = 'reg')
plt.show()

In [ ]:
plt.figure(figsize=(15,15))
mask = np.array(wine_corr)
mask[np.tril_indices_from(mask)] = False
sns.heatmap(wine_corr, mask = mask, annot=True, cmap='Blues')
plt.show()

In [ ]:
plt.figure(figsize=(15,5))
sns.boxplot(x = '와인품질', y = '알콜도수', data = wine)
plt.show()

In [ ]:
plt.figure(figsize=(15,5))
sns.boxplot(x = '와인품질', y = '밀도', data = wine)
plt.show()

In [ ]:
plt.figure(figsize=(8, 6)) 
sns.boxplot(x = '와인종류', y = '알콜도수', data = wine)
plt.grid()
plt.show()

In [ ]:
red = wine[wine.와인종류 == 'red']['알콜도수']
white = wine[wine.와인종류 == 'white']['알콜도수']

In [ ]:
tTestResult= stats.ttest_ind(red, white)
tTestResult

In [ ]:
red.mean()

In [ ]:
white.mean()

In [1]:
from sklearn.model_selection import LeaveOneOut

X = [1, 2, 3, 4]
loo = LeaveOneOut()
for train, test in loo.split(X):
    print("%s %s" % (train, test))

[1 2 3] [0]
[0 2 3] [1]
[0 1 3] [2]
[0 1 2] [3]
